### PR TITLE
Add gcc compliance

### PR DESCRIPTION
**Pull request by ghost**
On using gcc 6.2.0 2016-10-05, this game could not compile from errors `unused-result` and "implicit declaration of function".

The `unused-result` errors came from functions like `scanf` and `setgid` that returned non-void values. The "implicit declaration" error came from the function `srandom` which is not in the C99 standard, which is what the CFlag dictates.

Implicit declaration has been removed via the CFlag `-D_XOPEN_SOURCE=600`, and the `unused-result` errors have been downgraded to warnings via the CFLAG `-Wno-error=unused-result`.

I have also added the file `.gitignore` which ignores all object files and the `trek` binary itself.

### CODE REVIEW

**Comment by jj1bdx** [comment]
@Lawful-Lazy LGTM. This PR works OK on macOS 10.12.3 and FreeBSD amd64 11.0-STABLE. Duly merged. Thanks! :)
